!!python/object:rnn.data.Config
data_file: 'fixtures/trig.csv' # csv file to read as data
time_steps: 10
epochs_count: 100
n_features: 1
n_output_dim: 1
rnn_layers:
  - 10
rnn_in_keep: 1.0
rnn_out_keep: 1.0
batch_size: 1
lr: 0.1
